version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7
        environment:
          MAX_HEAP_SIZE: 4096m
          HEAP_NEWSIZE: 1024m
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker-compose up -d
      - run: docker-compose exec elija apk add --no-cache git
      - run: docker-compose exec elija pipenv install --dev
      - run: docker-compose exec elija pipenv run coverage run --source=application -m mamba.cli specs
      - run: docker-compose exec -e COVERALLS_REPO_TOKEN -e COVERALLS_SERVICE_NAME elija pipenv run coveralls
  lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install pipenv && pipenv install --dev
      - run: pipenv run pylint application/ specs/
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run: docker build -t bp2018hg1/elija:$CIRCLE_WORKFLOW_ID -t bp2018hg1/elija:latest .
      - run: docker push bp2018hg1/elija:$CIRCLE_WORKFLOW_ID
      - run: docker push bp2018hg1/elija:latest
  deploy:
    docker:
      - image: dtzar/helm-kubectl:2.11.0
    steps:
      - run: kubectl set image deployment elija elija=bp2018hg1/elija:$CIRCLE_WORKFLOW_ID --server=$KUBERNETES_SERVER --token=$KUBERNETES_BEARER_TOKEN
workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - lint
      - build:
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
